# Generated by Django 2.2.7 on 2019-11-28 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inlog', '0003_visitor_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='outtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
